[package]
name = "php-ext-tokenizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ext-php-rs = "0.12.0"
tokenizers = "0.15.2"

[lib]
crate-type = ["cdylib"]
